### ISSUE TITLE
Source Code Error

### ISSUE THREAD

**Issue by Aidan-The-Dev** [Nightmaregodss/minigames-discord#2]
Im trying to use the modmail function and I'm getting this error

```js
C:\Users\ocean\Documents\ac-modmail\node_modules\djs-easy\src\index.js:8
module.export.setup = require('./ticket')
                    ^

TypeError: Cannot set property 'setup' of undefined
    at Object.<anonymous> (C:\Users\ocean\Documents\ac-modmail\node_modules\djs-easy\src\index.js:8:21)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\ocean\Documents\ac-modmail\index.js:21:17)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
```

**Comment by nullure** [comment]
hmm ill try finding why the error is coused

**Comment by nullure** [comment]
hey i found the error this needs node.js v16 to run as its outdated currently and you are maybe using discord.js latest version
